=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
=end

fibonacci = [1,1]
incremento = 0
max_value = 0
suma = 0
while max_value <= 4000000
  new_value = fibonacci[incremento] + fibonacci[incremento + 1]
  fibonacci.push(new_value)
  incremento += 1
  max_value = new_value
  #sumamos solo los pares, son los mas valuados
  if new_value % 2 == 0
    suma += new_value
  end
end
puts fibonacci
puts 'La suma total es: %s' % suma
